baseURL = "https://urssi.us/"
languageCode = "en-us"
title = " Website of the US Research Software Sustainability Institute"
theme = "urssi"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

paginate = 4
paginatePath = "page"
rssLimit = 20

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
